name: Sync upstream

on:
  schedule:
    - cron: '0 3 * * *'  # každý den ve 3:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Add upstream and sync with master
        run: |
          git remote add upstream https://github.com/Klipper3d/klipper.git
          git fetch upstream
          git merge upstream/master --no-edit || true
          git push origin master || true

      - name: Merge master into dgus-integration
        run: |
          git fetch origin dgus-integration
          git reset --hard
          git clean -fd
          git checkout dgus-integration
          git merge master --no-edit || true
          git push origin dgus-integration || true
