name: Sync upstream

on:
  schedule:
    - cron: '0 3 * * *'  # denně ve 3 ráno
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git remote add upstream https://github.com/Klipper3d/klipper.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories --no-edit || true

      - name: Push changes
        run: |
          git push origin master || true
