name: Sync upstream

on:
  schedule:
    - cron: '0 3 * * *'  # každý den ve 3 ráno
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT_TOKEN }}

      - name: Reset working directory if needed
        run: |
          git reset --hard
          git clean -fd

      - name: Set up Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git remote add upstream https://github.com/Klipper3d/klipper.git
          git fetch upstream

      - name: Merge upstream/master into master
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --no-edit

      - name: Push changes to master
        run: git push origin master

      - name: Merge master into dgus-integration
        run: |
          git fetch origin dgus-integration
          git checkout dgus-integration
          git merge master --no-edit || true
          git push origin dgus-integration
      
      - name: Merge master into dgus-main
        run: |
          git fetch origin dgus-main
          git checkout dgus-main
          git merge master --no-edit || true
          git push origin dgus-main    
